/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/broadcasters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get broadcasters
         * @description Get information from the broadcasters table.
         */
        get: {
            parameters: {
                query: {
                    /**
                     * @description The wikis you want data from. Pipe-separate multiple wikis for multiwiki requests.
                     *
                     *     **Example:** `dota2`, `dota2|counterstrike`
                     */
                    wiki: components["parameters"]["wiki"];
                    /**
                     * @description The filters you want to apply to the request.
                     *
                     *     **Example:** `[[pagename::Some/Liquipedia/Page]] AND [[namespace::0]]`
                     */
                    conditions?: components["parameters"]["conditions"];
                    /**
                     * @description The datapoints you want to query.
                     *
                     *     **Example:** `pagename, pageid, namespace`
                     */
                    query?: components["parameters"]["query"];
                    /**
                     * @description The amount of results you want.
                     *
                     *     **Example:** `20`
                     */
                    limit?: components["parameters"]["limit"];
                    /**
                     * @description This can be used for pagination.
                     *
                     *     **Example:** `20`
                     */
                    offset?: components["parameters"]["offset"];
                    /**
                     * @description The order you want your result in.
                     *
                     *     **Example:** `pagename ASC`
                     */
                    order?: components["parameters"]["order"];
                    /**
                     * @description What you want your results grouped by (this can be helpful when using aggregate functions).
                     *
                     *     **Example:** `pagename ASC`
                     */
                    groupby?: components["parameters"]["groupby"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful call */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["successfulResponse"] | components["schemas"]["successfulResponseWithWarning"];
                    };
                };
                /** @description Invalid API key */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description Asking for data that does not exist */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description Over API limit */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/company": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get companies
         * @description Get information from the company table.
         */
        get: {
            parameters: {
                query: {
                    /**
                     * @description The wikis you want data from. Pipe-separate multiple wikis for multiwiki requests.
                     *
                     *     **Example:** `dota2`, `dota2|counterstrike`
                     */
                    wiki: components["parameters"]["wiki"];
                    /**
                     * @description The filters you want to apply to the request.
                     *
                     *     **Example:** `[[pagename::Some/Liquipedia/Page]] AND [[namespace::0]]`
                     */
                    conditions?: components["parameters"]["conditions"];
                    /**
                     * @description The datapoints you want to query.
                     *
                     *     **Example:** `pagename, pageid, namespace`
                     */
                    query?: components["parameters"]["query"];
                    /**
                     * @description The amount of results you want.
                     *
                     *     **Example:** `20`
                     */
                    limit?: components["parameters"]["limit"];
                    /**
                     * @description This can be used for pagination.
                     *
                     *     **Example:** `20`
                     */
                    offset?: components["parameters"]["offset"];
                    /**
                     * @description The order you want your result in.
                     *
                     *     **Example:** `pagename ASC`
                     */
                    order?: components["parameters"]["order"];
                    /**
                     * @description What you want your results grouped by (this can be helpful when using aggregate functions).
                     *
                     *     **Example:** `pagename ASC`
                     */
                    groupby?: components["parameters"]["groupby"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful call */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["successfulResponse"] | components["schemas"]["successfulResponseWithWarning"];
                    };
                };
                /** @description Invalid API key */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description Asking for data that does not exist */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description Over API limit */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datapoint": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get datapoints
         * @description Get information from the datapoint table. This information is unspecified between wikis and can hold a variety of things.
         */
        get: {
            parameters: {
                query: {
                    /**
                     * @description The wikis you want data from. Pipe-separate multiple wikis for multiwiki requests.
                     *
                     *     **Example:** `dota2`, `dota2|counterstrike`
                     */
                    wiki: components["parameters"]["wiki"];
                    /**
                     * @description The filters you want to apply to the request.
                     *
                     *     **Example:** `[[pagename::Some/Liquipedia/Page]] AND [[namespace::0]]`
                     */
                    conditions?: components["parameters"]["conditions"];
                    /**
                     * @description The datapoints you want to query.
                     *
                     *     **Example:** `pagename, pageid, namespace`
                     */
                    query?: components["parameters"]["query"];
                    /**
                     * @description The amount of results you want.
                     *
                     *     **Example:** `20`
                     */
                    limit?: components["parameters"]["limit"];
                    /**
                     * @description This can be used for pagination.
                     *
                     *     **Example:** `20`
                     */
                    offset?: components["parameters"]["offset"];
                    /**
                     * @description The order you want your result in.
                     *
                     *     **Example:** `pagename ASC`
                     */
                    order?: components["parameters"]["order"];
                    /**
                     * @description What you want your results grouped by (this can be helpful when using aggregate functions).
                     *
                     *     **Example:** `pagename ASC`
                     */
                    groupby?: components["parameters"]["groupby"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful call */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["successfulResponse"] | components["schemas"]["successfulResponseWithWarning"];
                    };
                };
                /** @description Invalid API key */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description Asking for data that does not exist */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description Over API limit */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/externalmedialink": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get media links
         * @description Get information from the externalmedialink table.
         */
        get: {
            parameters: {
                query: {
                    /**
                     * @description The wikis you want data from. Pipe-separate multiple wikis for multiwiki requests.
                     *
                     *     **Example:** `dota2`, `dota2|counterstrike`
                     */
                    wiki: components["parameters"]["wiki"];
                    /**
                     * @description The filters you want to apply to the request.
                     *
                     *     **Example:** `[[pagename::Some/Liquipedia/Page]] AND [[namespace::0]]`
                     */
                    conditions?: components["parameters"]["conditions"];
                    /**
                     * @description The datapoints you want to query.
                     *
                     *     **Example:** `pagename, pageid, namespace`
                     */
                    query?: components["parameters"]["query"];
                    /**
                     * @description The amount of results you want.
                     *
                     *     **Example:** `20`
                     */
                    limit?: components["parameters"]["limit"];
                    /**
                     * @description This can be used for pagination.
                     *
                     *     **Example:** `20`
                     */
                    offset?: components["parameters"]["offset"];
                    /**
                     * @description The order you want your result in.
                     *
                     *     **Example:** `pagename ASC`
                     */
                    order?: components["parameters"]["order"];
                    /**
                     * @description What you want your results grouped by (this can be helpful when using aggregate functions).
                     *
                     *     **Example:** `pagename ASC`
                     */
                    groupby?: components["parameters"]["groupby"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful call */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["successfulResponse"] | components["schemas"]["successfulResponseWithWarning"];
                    };
                };
                /** @description Invalid API key */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description Asking for data that does not exist */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description Over API limit */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/match": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get matches
         * @description Get information from the match2 table.
         */
        get: {
            parameters: {
                query: {
                    /**
                     * @description The wikis you want data from. Pipe-separate multiple wikis for multiwiki requests.
                     *
                     *     **Example:** `dota2`, `dota2|counterstrike`
                     */
                    wiki: components["parameters"]["wiki"];
                    /**
                     * @description The filters you want to apply to the request.
                     *
                     *     **Example:** `[[pagename::Some/Liquipedia/Page]] AND [[namespace::0]]`
                     */
                    conditions?: components["parameters"]["conditions"];
                    /**
                     * @description The datapoints you want to query.
                     *
                     *     **Example:** `pagename, pageid, namespace`
                     */
                    query?: components["parameters"]["query"];
                    /**
                     * @description The amount of results you want.
                     *
                     *     **Example:** `20`
                     */
                    limit?: components["parameters"]["limit"];
                    /**
                     * @description This can be used for pagination.
                     *
                     *     **Example:** `20`
                     */
                    offset?: components["parameters"]["offset"];
                    /**
                     * @description The order you want your result in.
                     *
                     *     **Example:** `pagename ASC`
                     */
                    order?: components["parameters"]["order"];
                    /**
                     * @description What you want your results grouped by (this can be helpful when using aggregate functions).
                     *
                     *     **Example:** `pagename ASC`
                     */
                    groupby?: components["parameters"]["groupby"];
                    /**
                     * @description If you want the raw stream data. Read the full documentation on how this correlates with `streamurls`.
                     *
                     *     **Example:** `true`, `false`
                     */
                    rawstreams?: "true" | "false";
                    /**
                     * @description If you want to get stream urls to link to. Read the full documentation on how this correlates with `rawstreams`.
                     *
                     *     **Example:** `true`, `false`
                     */
                    streamurls?: "true" | "false";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful call */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["successfulResponse"] | components["schemas"]["successfulResponseWithWarning"];
                    };
                };
                /** @description Invalid API key */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description Asking for data that does not exist */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description Over API limit */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/placement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get placements
         * @description Get information from the placement table.
         */
        get: {
            parameters: {
                query: {
                    /**
                     * @description The wikis you want data from. Pipe-separate multiple wikis for multiwiki requests.
                     *
                     *     **Example:** `dota2`, `dota2|counterstrike`
                     */
                    wiki: components["parameters"]["wiki"];
                    /**
                     * @description The filters you want to apply to the request.
                     *
                     *     **Example:** `[[pagename::Some/Liquipedia/Page]] AND [[namespace::0]]`
                     */
                    conditions?: components["parameters"]["conditions"];
                    /**
                     * @description The datapoints you want to query.
                     *
                     *     **Example:** `pagename, pageid, namespace`
                     */
                    query?: components["parameters"]["query"];
                    /**
                     * @description The amount of results you want.
                     *
                     *     **Example:** `20`
                     */
                    limit?: components["parameters"]["limit"];
                    /**
                     * @description This can be used for pagination.
                     *
                     *     **Example:** `20`
                     */
                    offset?: components["parameters"]["offset"];
                    /**
                     * @description The order you want your result in.
                     *
                     *     **Example:** `pagename ASC`
                     */
                    order?: components["parameters"]["order"];
                    /**
                     * @description What you want your results grouped by (this can be helpful when using aggregate functions).
                     *
                     *     **Example:** `pagename ASC`
                     */
                    groupby?: components["parameters"]["groupby"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful call */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["successfulResponse"] | components["schemas"]["successfulResponseWithWarning"];
                    };
                };
                /** @description Invalid API key */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description Asking for data that does not exist */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description Over API limit */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/player": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get players
         * @description Get information from the player table.
         */
        get: {
            parameters: {
                query: {
                    /**
                     * @description The wikis you want data from. Pipe-separate multiple wikis for multiwiki requests.
                     *
                     *     **Example:** `dota2`, `dota2|counterstrike`
                     */
                    wiki: components["parameters"]["wiki"];
                    /**
                     * @description The filters you want to apply to the request.
                     *
                     *     **Example:** `[[pagename::Some/Liquipedia/Page]] AND [[namespace::0]]`
                     */
                    conditions?: components["parameters"]["conditions"];
                    /**
                     * @description The datapoints you want to query.
                     *
                     *     **Example:** `pagename, pageid, namespace`
                     */
                    query?: components["parameters"]["query"];
                    /**
                     * @description The amount of results you want.
                     *
                     *     **Example:** `20`
                     */
                    limit?: components["parameters"]["limit"];
                    /**
                     * @description This can be used for pagination.
                     *
                     *     **Example:** `20`
                     */
                    offset?: components["parameters"]["offset"];
                    /**
                     * @description The order you want your result in.
                     *
                     *     **Example:** `pagename ASC`
                     */
                    order?: components["parameters"]["order"];
                    /**
                     * @description What you want your results grouped by (this can be helpful when using aggregate functions).
                     *
                     *     **Example:** `pagename ASC`
                     */
                    groupby?: components["parameters"]["groupby"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful call */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["successfulResponse"] | components["schemas"]["successfulResponseWithWarning"];
                    };
                };
                /** @description Invalid API key */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description Asking for data that does not exist */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description Over API limit */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get series
         * @description Get information from the series table.
         */
        get: {
            parameters: {
                query: {
                    /**
                     * @description The wikis you want data from. Pipe-separate multiple wikis for multiwiki requests.
                     *
                     *     **Example:** `dota2`, `dota2|counterstrike`
                     */
                    wiki: components["parameters"]["wiki"];
                    /**
                     * @description The filters you want to apply to the request.
                     *
                     *     **Example:** `[[pagename::Some/Liquipedia/Page]] AND [[namespace::0]]`
                     */
                    conditions?: components["parameters"]["conditions"];
                    /**
                     * @description The datapoints you want to query.
                     *
                     *     **Example:** `pagename, pageid, namespace`
                     */
                    query?: components["parameters"]["query"];
                    /**
                     * @description The amount of results you want.
                     *
                     *     **Example:** `20`
                     */
                    limit?: components["parameters"]["limit"];
                    /**
                     * @description This can be used for pagination.
                     *
                     *     **Example:** `20`
                     */
                    offset?: components["parameters"]["offset"];
                    /**
                     * @description The order you want your result in.
                     *
                     *     **Example:** `pagename ASC`
                     */
                    order?: components["parameters"]["order"];
                    /**
                     * @description What you want your results grouped by (this can be helpful when using aggregate functions).
                     *
                     *     **Example:** `pagename ASC`
                     */
                    groupby?: components["parameters"]["groupby"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful call */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["successfulResponse"] | components["schemas"]["successfulResponseWithWarning"];
                    };
                };
                /** @description Invalid API key */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description Asking for data that does not exist */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description Over API limit */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/squadplayer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get squadplayer
         * @description Get information from the squadplayer table.
         */
        get: {
            parameters: {
                query: {
                    /**
                     * @description The wikis you want data from. Pipe-separate multiple wikis for multiwiki requests.
                     *
                     *     **Example:** `dota2`, `dota2|counterstrike`
                     */
                    wiki: components["parameters"]["wiki"];
                    /**
                     * @description The filters you want to apply to the request.
                     *
                     *     **Example:** `[[pagename::Some/Liquipedia/Page]] AND [[namespace::0]]`
                     */
                    conditions?: components["parameters"]["conditions"];
                    /**
                     * @description The datapoints you want to query.
                     *
                     *     **Example:** `pagename, pageid, namespace`
                     */
                    query?: components["parameters"]["query"];
                    /**
                     * @description The amount of results you want.
                     *
                     *     **Example:** `20`
                     */
                    limit?: components["parameters"]["limit"];
                    /**
                     * @description This can be used for pagination.
                     *
                     *     **Example:** `20`
                     */
                    offset?: components["parameters"]["offset"];
                    /**
                     * @description The order you want your result in.
                     *
                     *     **Example:** `pagename ASC`
                     */
                    order?: components["parameters"]["order"];
                    /**
                     * @description What you want your results grouped by (this can be helpful when using aggregate functions).
                     *
                     *     **Example:** `pagename ASC`
                     */
                    groupby?: components["parameters"]["groupby"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful call */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["successfulResponse"] | components["schemas"]["successfulResponseWithWarning"];
                    };
                };
                /** @description Invalid API key */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description Asking for data that does not exist */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description Over API limit */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/standingsentry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get standing
         * @description Get information from the standing entries table.
         */
        get: {
            parameters: {
                query: {
                    /**
                     * @description The wikis you want data from. Pipe-separate multiple wikis for multiwiki requests.
                     *
                     *     **Example:** `dota2`, `dota2|counterstrike`
                     */
                    wiki: components["parameters"]["wiki"];
                    /**
                     * @description The filters you want to apply to the request.
                     *
                     *     **Example:** `[[pagename::Some/Liquipedia/Page]] AND [[namespace::0]]`
                     */
                    conditions?: components["parameters"]["conditions"];
                    /**
                     * @description The datapoints you want to query.
                     *
                     *     **Example:** `pagename, pageid, namespace`
                     */
                    query?: components["parameters"]["query"];
                    /**
                     * @description The amount of results you want.
                     *
                     *     **Example:** `20`
                     */
                    limit?: components["parameters"]["limit"];
                    /**
                     * @description This can be used for pagination.
                     *
                     *     **Example:** `20`
                     */
                    offset?: components["parameters"]["offset"];
                    /**
                     * @description The order you want your result in.
                     *
                     *     **Example:** `pagename ASC`
                     */
                    order?: components["parameters"]["order"];
                    /**
                     * @description What you want your results grouped by (this can be helpful when using aggregate functions).
                     *
                     *     **Example:** `pagename ASC`
                     */
                    groupby?: components["parameters"]["groupby"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful call */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["successfulResponse"] | components["schemas"]["successfulResponseWithWarning"];
                    };
                };
                /** @description Invalid API key */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description Asking for data that does not exist */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description Over API limit */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/standingstable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get standing
         * @description Get information from the standing table.
         */
        get: {
            parameters: {
                query: {
                    /**
                     * @description The wikis you want data from. Pipe-separate multiple wikis for multiwiki requests.
                     *
                     *     **Example:** `dota2`, `dota2|counterstrike`
                     */
                    wiki: components["parameters"]["wiki"];
                    /**
                     * @description The filters you want to apply to the request.
                     *
                     *     **Example:** `[[pagename::Some/Liquipedia/Page]] AND [[namespace::0]]`
                     */
                    conditions?: components["parameters"]["conditions"];
                    /**
                     * @description The datapoints you want to query.
                     *
                     *     **Example:** `pagename, pageid, namespace`
                     */
                    query?: components["parameters"]["query"];
                    /**
                     * @description The amount of results you want.
                     *
                     *     **Example:** `20`
                     */
                    limit?: components["parameters"]["limit"];
                    /**
                     * @description This can be used for pagination.
                     *
                     *     **Example:** `20`
                     */
                    offset?: components["parameters"]["offset"];
                    /**
                     * @description The order you want your result in.
                     *
                     *     **Example:** `pagename ASC`
                     */
                    order?: components["parameters"]["order"];
                    /**
                     * @description What you want your results grouped by (this can be helpful when using aggregate functions).
                     *
                     *     **Example:** `pagename ASC`
                     */
                    groupby?: components["parameters"]["groupby"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful call */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["successfulResponse"] | components["schemas"]["successfulResponseWithWarning"];
                    };
                };
                /** @description Invalid API key */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description Asking for data that does not exist */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description Over API limit */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/team": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get teams
         * @description Get information from the team table.
         */
        get: {
            parameters: {
                query: {
                    /**
                     * @description The wikis you want data from. Pipe-separate multiple wikis for multiwiki requests.
                     *
                     *     **Example:** `dota2`, `dota2|counterstrike`
                     */
                    wiki: components["parameters"]["wiki"];
                    /**
                     * @description The filters you want to apply to the request.
                     *
                     *     **Example:** `[[pagename::Some/Liquipedia/Page]] AND [[namespace::0]]`
                     */
                    conditions?: components["parameters"]["conditions"];
                    /**
                     * @description The datapoints you want to query.
                     *
                     *     **Example:** `pagename, pageid, namespace`
                     */
                    query?: components["parameters"]["query"];
                    /**
                     * @description The amount of results you want.
                     *
                     *     **Example:** `20`
                     */
                    limit?: components["parameters"]["limit"];
                    /**
                     * @description This can be used for pagination.
                     *
                     *     **Example:** `20`
                     */
                    offset?: components["parameters"]["offset"];
                    /**
                     * @description The order you want your result in.
                     *
                     *     **Example:** `pagename ASC`
                     */
                    order?: components["parameters"]["order"];
                    /**
                     * @description What you want your results grouped by (this can be helpful when using aggregate functions).
                     *
                     *     **Example:** `pagename ASC`
                     */
                    groupby?: components["parameters"]["groupby"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful call */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["successfulResponse"] | components["schemas"]["successfulResponseWithWarning"];
                    };
                };
                /** @description Invalid API key */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description Asking for data that does not exist */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description Over API limit */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teamtemplate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a team template
         * @description Use this to get a single team template.
         */
        get: {
            parameters: {
                query: {
                    /**
                     * @description The wiki you want data from.
                     *
                     *     **Example:** `dota2`
                     */
                    wiki: string;
                    /**
                     * @description The template name of the team template you want to get.
                     *
                     *     **Example:** `teamliquid`
                     */
                    template: string;
                    /**
                     * @description Liquipedia supports historical logos, but will require the date to show them.
                     *
                     *     **Example:** `2009-06-05`
                     */
                    date?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful call */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["successfulResponse"] | components["schemas"]["successfulResponseWithWarning"];
                    };
                };
                /** @description Invalid API key */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description Asking for data that does not exist */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description Over API limit */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teamtemplatelist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a list of team templates
         * @description Use this to query a list of team templates in pages of 200.
         */
        get: {
            parameters: {
                query: {
                    /**
                     * @description The wiki you want data from.
                     *
                     *     **Example:** `dota2`
                     */
                    wiki: string;
                    /**
                     * @description .
                     *
                     *     **Example:** `1`
                     */
                    pagination?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful call */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["successfulResponse"] | components["schemas"]["successfulResponseWithWarning"];
                    };
                };
                /** @description Invalid API key */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description Asking for data that does not exist */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description Over API limit */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tournament": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get tournaments
         * @description Get information from the tournament table.
         */
        get: {
            parameters: {
                query: {
                    /**
                     * @description The wikis you want data from. Pipe-separate multiple wikis for multiwiki requests.
                     *
                     *     **Example:** `dota2`, `dota2|counterstrike`
                     */
                    wiki: components["parameters"]["wiki"];
                    /**
                     * @description The filters you want to apply to the request.
                     *
                     *     **Example:** `[[pagename::Some/Liquipedia/Page]] AND [[namespace::0]]`
                     */
                    conditions?: components["parameters"]["conditions"];
                    /**
                     * @description The datapoints you want to query.
                     *
                     *     **Example:** `pagename, pageid, namespace`
                     */
                    query?: components["parameters"]["query"];
                    /**
                     * @description The amount of results you want.
                     *
                     *     **Example:** `20`
                     */
                    limit?: components["parameters"]["limit"];
                    /**
                     * @description This can be used for pagination.
                     *
                     *     **Example:** `20`
                     */
                    offset?: components["parameters"]["offset"];
                    /**
                     * @description The order you want your result in.
                     *
                     *     **Example:** `pagename ASC`
                     */
                    order?: components["parameters"]["order"];
                    /**
                     * @description What you want your results grouped by (this can be helpful when using aggregate functions).
                     *
                     *     **Example:** `pagename ASC`
                     */
                    groupby?: components["parameters"]["groupby"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful call */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["successfulResponse"] | components["schemas"]["successfulResponseWithWarning"];
                    };
                };
                /** @description Invalid API key */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description Asking for data that does not exist */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description Over API limit */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transfer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get transfers
         * @description Get information from the transfer table.
         */
        get: {
            parameters: {
                query: {
                    /**
                     * @description The wikis you want data from. Pipe-separate multiple wikis for multiwiki requests.
                     *
                     *     **Example:** `dota2`, `dota2|counterstrike`
                     */
                    wiki: components["parameters"]["wiki"];
                    /**
                     * @description The filters you want to apply to the request.
                     *
                     *     **Example:** `[[pagename::Some/Liquipedia/Page]] AND [[namespace::0]]`
                     */
                    conditions?: components["parameters"]["conditions"];
                    /**
                     * @description The datapoints you want to query.
                     *
                     *     **Example:** `pagename, pageid, namespace`
                     */
                    query?: components["parameters"]["query"];
                    /**
                     * @description The amount of results you want.
                     *
                     *     **Example:** `20`
                     */
                    limit?: components["parameters"]["limit"];
                    /**
                     * @description This can be used for pagination.
                     *
                     *     **Example:** `20`
                     */
                    offset?: components["parameters"]["offset"];
                    /**
                     * @description The order you want your result in.
                     *
                     *     **Example:** `pagename ASC`
                     */
                    order?: components["parameters"]["order"];
                    /**
                     * @description What you want your results grouped by (this can be helpful when using aggregate functions).
                     *
                     *     **Example:** `pagename ASC`
                     */
                    groupby?: components["parameters"]["groupby"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful call */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["successfulResponse"] | components["schemas"]["successfulResponseWithWarning"];
                    };
                };
                /** @description Invalid API key */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description Asking for data that does not exist */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description Over API limit */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Successful call */
        successfulResponse: {
            result?: Record<string, never>[];
        };
        /** Successful call with warning */
        successfulResponseWithWarning: {
            result?: Record<string, never>[];
            warning?: string[];
        };
        /** Error */
        error: {
            error?: string[];
        };
    };
    responses: never;
    parameters: {
        /**
         * @description The wikis you want data from. Pipe-separate multiple wikis for multiwiki requests.
         *
         *     **Example:** `dota2`, `dota2|counterstrike`
         */
        wiki: string;
        /**
         * @description The filters you want to apply to the request.
         *
         *     **Example:** `[[pagename::Some/Liquipedia/Page]] AND [[namespace::0]]`
         */
        conditions: string;
        /**
         * @description The datapoints you want to query.
         *
         *     **Example:** `pagename, pageid, namespace`
         */
        query: string;
        /**
         * @description The amount of results you want.
         *
         *     **Example:** `20`
         */
        limit: number;
        /**
         * @description This can be used for pagination.
         *
         *     **Example:** `20`
         */
        offset: number;
        /**
         * @description The order you want your result in.
         *
         *     **Example:** `pagename ASC`
         */
        order: string;
        /**
         * @description What you want your results grouped by (this can be helpful when using aggregate functions).
         *
         *     **Example:** `pagename ASC`
         */
        groupby: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
